### ISSUE TITLE
Creation of Picture object in thread halts execution

### ISSUE THREAD

**Issue by lzkof** [CynxCode/OpenWcs#5]
- timelapse.cpp - Timelapse::snapPicture ...
  - stops at "_cap=0" in Picture::Picture with no error message
- only on MacOSX (it works perfectly on Linux)

**Comment by SydoxX** [comment]
We'll move this back as Mac OS isn't our main target for this project.

**Comment by SydoxX** [comment]
@Ballonen Is this still a problem on Mac?
